builds:
  - binary: multi-k8s
    goos:
      - darwin
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w -X github.com/andrei-don/multi-k8s/cmd.Version=v{{.Version}}

brews:
  - 
    name: multi-k8s
    homepage: https://github.com/andrei-don/multi-k8s
    description: "CLI to create k8s clusters on Multipass VMs."
    repository:
      owner: andrei-don
      name: homebrew-tap
      branch: main

checksum:
  name_template: 'checksums.txt'
    