package k8s

import (
	"fmt"

	"github.com/andrei-don/multi-k8s/multipass"
)

// DeleteClusterVMs takes the list of nodes generated by GetCurrentNodes as input and deletes each one with the multipass.Delete method.
func DeleteClusterVMs(clusterNodes []string) error {
	for _, node := range clusterNodes {
		err := multipass.Delete(&multipass.DeleteReq{Name: node})
		if err != nil {
			fmt.Println(err)
			return err
		}
		fmt.Printf("Deleted node %v!\n", node)
	}
	return nil
}
